export { ReactComponent as Lupa } from './iconoLupa.svg'
export { ReactComponent as Inicio } from './inicio.svg'
export { ReactComponent as Nuevo } from './nuevo.svg'
export { ReactComponent as Usuario } from './usuario.svg'
export { ReactComponent as Esp } from './esp.svg'
export { ReactComponent as Eng } from './eng.svg'